### ISSUE TITLE
[KWOC] PDF Reader Project

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [shrey141102/PythonProjects#116]
- I would like to add the pdf reader python project.
- This will help user to listen their pdf files, any kind of short notes, guidelines, books, etc which are in pdf form.
- And saves a lot of time of the user.

**Comment by Avdhesh-Varshney** [comment]
@shrey141102 please assign this project to me to contribute under KWOC

**Comment by shrey141102** [comment]
yes
