### ISSUE TITLE
[KWOC] Wishing Bot Model

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [shrey141102/PythonProjects#117]
- To wish or greet people in a coding style along with a background music.
- Asking of the occasion which will occur or you want to greet people.
- Then playing the song in the background related to that occasion.
- Creating different types of the emojis.
- Adding announcement of that occasion will makes it more attractive.

**Comment by Avdhesh-Varshney** [comment]
@shrey141102 please assign this project to me to contribute in your repo under KWOC program

**Comment by shrey141102** [comment]
seems nice
