### ISSUE TITLE
Tic-Tac-Toe Game

### ISSUE THREAD

**Issue by shrey141102** [shrey141102/PythonProjects#20]
Make an interactive TIc-Tac-Toe game 
Can be web based or Text based on inputs with proper representation of the table

**Comment by ArkaMandal16** [comment]
@shrey141102 so build it and add to the repo?

**Comment by shrey141102** [comment]
yup

**Comment by Aryanmartinian** [comment]
Hi I would like to contribute to this under KWOC'23
Full Name - Aryan Mishra
Github Profile Link: https://github.com/Aryanmartinian
Participant id:NA
What is your participant role: Contributor(kwoc'23)

**Comment by shrey141102** [comment]
sure @Aryanmartinian

**Comment by mitaliruhela** [comment]
hey, can you assign me this issue.

**Comment by shrey141102** [comment]
Closing this
