### ISSUE TITLE
Build a typing tester

### ISSUE THREAD

**Issue by shrey141102** [shrey141102/PythonProjects#21]
Build a typing tester. This should show the user some text, and then challenge them to type it — while timing them and scoring them on for accuracy.

**Comment by kausthub-kannan** [comment]
Hello, I would like to work in this issue
Can you assign it to me? I have register for KWoC2023

**Comment by Arpit01Goel** [comment]
Sorry but I already made one. Please let mine be used.

**Comment by shrey141102** [comment]
Hey @kausthub-kannan @Arpit01Goel can you guys decide among yourselves who will tak eup this issue?? I'll assign accordingly

**Comment by kausthub-kannan** [comment]
@Arpit01Goel has written code for pretty much most of the Issues, I can take up this issue if he is ok with it

**Comment by Arpit01Goel** [comment]
@kausthub-kannan I haven't got any satisfying issue for myself. You can make the typing one .

**Comment by shrey141102** [comment]
don

**Comment by kausthub-kannan** [comment]
Should this be CLI or GUI based?

**Comment by shrey141102** [comment]
thanks for contributing man
either one is fine 👍🏻 
But ig GUI will be better
