### ISSUE TITLE
Add games

### ISSUE THREAD

**Issue by Arpit01Goel** [shrey141102/PythonProjects#24]
I have wrote the code for vigenere cypher, modified vigenere cypher , tic-tac-toe, typing speed and accuracy test .

**Comment by shrey141102** [comment]
Hey @Arpit01Goel , Lets go one project at a time. Shall we?

**Comment by Arpit01Goel** [comment]
okey juat add my vigenere cypher's 2 codes.

**Comment by shrey141102** [comment]
> okey just add my vigenere cypher's 2 codes.

make a PR based on that

**Comment by Ananya-m0140** [comment]
I have written the code for a simple car game.Can that be added?

**Comment by Arpit01Goel** [comment]
@Ananya-m0140 Ma'am , this issue was raised to add my games . Your game may definately be added , please raise another issue for that game . This issue is closed now .
