### ISSUE TITLE
Movie Recommendation System:

### ISSUE THREAD

**Issue by shrey141102** [shrey141102/PythonProjects#4]
- Develop a movie recommendation system based on user preferences. You can use collaborative filtering or content-based filtering algorithms.

**Comment by onkar-1432** [comment]
@shrey141102 please allow me to work on these issue for Kwoc2023

**Comment by shrey141102** [comment]
Hey guys, you can work on it

**Comment by mitaliruhela** [comment]
Hey , Can you assign me this issue, I try my best to solve. Also, am I late to contribute for this project?

**Comment by shrey141102** [comment]
> Hey , Can you assign me this issue, I try my best to solve. Also, am I late to contribute for this project?

Nope, you are not late.
Yes, you can try no issues 😄

**Comment by saurav-dhait** [comment]
hey can you assign me this issue ?

**Comment by mitaliruhela** [comment]
Thanks for assigning.

**Comment by mitaliruhela** [comment]
As issue#4 is already marked as completed, so can we still contribute to
this issue?
Actually I just learning how GitHub works.
Therefore having so many doubts.😅

**Comment by saurav-dhait** [comment]
i dont think so this issue is completed, 
i sent him a PR for this issue which is still pending .
most probably this was by mistake marked as completed since there is no movie recommendation  system in repository.

**Comment by mitaliruhela** [comment]
Ok, thanks for the update.

**Comment by mitaliruhela** [comment]
Also,do we use the same data set which is given on GitHub or it is just the
sample data set?
