### ISSUE TITLE
GUI for Hangman-Game

### ISSUE THREAD

**Issue by shubha987** [shrey141102/PythonProjects#50]
![Screenshot 2023-12-12 200849](https://github.com/shrey141102/PythonProjects/assets/116547779/a043b8ad-2b56-424f-9b2e-cd49428a73ad)
Somehow it will look like it.

@shrey141102  please assign me the issue

**Comment by shrey141102** [comment]
@shubha987 try adding the hanging man image also, you know like their legs/arms are cutting off with each wrong guess..

**Comment by shubha987** [comment]
Ok let me try for it.

**Comment by shubha987** [comment]
![Screenshot 2023-12-12 221617](https://github.com/shrey141102/PythonProjects/assets/116547779/58b43437-5535-4eba-b8c9-3b5854a75231)
I have done it like that. is it okay?

**Comment by shrey141102** [comment]
Yup man looks good

**Comment by shubha987** [comment]
ok @shrey141102 assign me then i am creating pull request

**Comment by shrey141102** [comment]
Its done
