### ISSUE TITLE
color print

### ISSUE THREAD

**Issue by Tanmay0215** [shrey141102/PythonProjects#66]
using colorama library we can create a code which gives a colourful output

**Comment by shrey141102** [comment]
screenshot pls

**Comment by Tanmay0215** [comment]
<img width="488" alt="image" src="https://github.com/shrey141102/PythonProjects/assets/134931600/cec68424-e422-4511-af8f-f8a02f4b1f83">

**Comment by shrey141102** [comment]
closing this
