### ISSUE TITLE
guess the word game

### ISSUE THREAD

**Issue by Tanmay0215** [shrey141102/PythonProjects#69]
guess the word game #kwoc

**Comment by Yarlin16** [comment]
Can you please elaborate more??  cuz I guess I'm thinking of a similar idea. Just to make sure whether mine is alike or not..

**Comment by Tanmay0215** [comment]
this would be just a basic python code which first gives choice to user about which field relates or totally random then from that field chooses a word then jumbles it and outputs then input the user answer if correct right else wrong guess

**Comment by shrey141102** [comment]
Whats going on guys...

**Comment by Tanmay0215** [comment]
import random

sports = [
    "athlete", "baseball", "basketball", "coach", "competition", "cycling", "fitness", "football",
    "golfer", "gymnast", "hockey", "lacrosse", "paddle", "referee", "sailing", "skating", "soccer",
    "swimmer", "table tennis", "tennis", "volleyball", "wrestling"
]

social_media = [
    "facebook", "twitter", "instagram", "linkedin", "snapchat", "tiktok", "pinterest", "youtube",
    "reddit", "vimeo", "spotify", "medium", "whatsapp", "skype", "slack", "discord", "telegram", "wechat", "viber"
]

languages = ['Python', 'Java', 'C++', 'JavaScript', 'Ruby', 'Swift', 'PHP', 'Kotlin', 'C#', 'TypeScript', 'Go', 'Scala', 'Rust', 
             'Dart', 'Objective-C', 'ReactJS', 'VueJS', 'AngularJS', 'Flutter', 'SQL', 'HTML', 'CSS', 'SASS', 'LESS', 'SCSS', 'ASP.NET'
             , 'Perl', 'Shell', 'Fortran', 'Visual Basic', 'Pascal', 'Clojure', 'Erlang', 'Elixir', 'R', 
             'Haskell', 'Rust', 'Nim', 'MATLAB']

code_editors = ['Visual Studio Code', 'Sublime Text', 'Atom', 'Notepad++', 'IntelliJ IDEA', 
                        'Eclipse', 'PyCharm', 'VSCode', 'Code::Blocks', 'NetBeans', 'CodeLite', 'BlueJ',
                        'Aptana', 'AppCode', 'LightTable', 'Spacemacs', 'SlickEdit', 'Rider',
                        'Vim', 'Emacs', 'nano', 'Kate', 'TextMate', 'CodeSandbox', 'Xcode', 'RStudio'
                        , 'CLion', 'Gedit', 'NetBeans', 'Monodevelop', 'IntelliJ IDEA', 'TextWrangler', 
                        'Visual Studio', 'Goorm', 'PhpStorm', 'RubyMine', 'WebStorm', 'Rider', '0xDBE', 'Gallium']

type = [sports, social_media, languages, code_editors]

# match choice:
#     case "languages", "lang":
#         topic = languages
#     case "social_media" "sm":
#         topic = social_media

word = type
shuffledword = random.choice(type)
random.shuffle(shuffledword)

print("Jumbled word is:")
for i in shuffledword:
    print(i, end="")
print()

# print("Jumbled Sports Word:", shuffledword)

guess = input().lower().strip()
if word == guess:
    print("Success")
    
else:
	print("Wrong Guess")

I am creating a basic jumbled words guess the word game once send the as I finish it

**Comment by shrey141102** [comment]
i still didnt understand what this project is about..
