### ISSUE TITLE
ASCII Code

### ISSUE THREAD

**Issue by Tanmay0215** [shrey141102/PythonProjects#70]
based on using ascii characters

**Comment by shrey141102** [comment]
????

**Comment by Tanmay0215** [comment]
i have added a code apprently its with color print pr could see if its possible to merge
i am adding the supporting images
<img width="463" alt="Screenshot 2023-12-22 233054" src="https://github.com/shrey141102/PythonProjects/assets/134931600/e570e0e3-c4ea-43d3-b6e0-a477d5c892e6">
<img width="239" alt="Screenshot 2023-12-22 233334" src="https://github.com/shrey141102/PythonProjects/assets/134931600/5445552b-7e56-48cf-9c0b-e5985f973bf6">
<img width="532" alt="Screenshot 2023-12-22 233408" src="https://github.com/shrey141102/PythonProjects/assets/134931600/e63fc5cb-20a3-4087-a52c-191f37193d0a">

**Comment by shrey141102** [comment]
okay bro go ahead

**Comment by Tanmay0215** [comment]
its done
